<div class="entry-edit-head collapseable"> <a>Errors</a> </div>
<fieldset class="grid">
    <table class="border">
        <thead>
            <tr class="headings">
                <th>File</th>
                <th>Deviation</th>
            </tr>
        </thead>
        <tbody>
            <?php $errors = $this->getErrors(); ?>
            <?php foreach ($errors as $file => $error) : ?>
                <tr class="<?php echo $this->getParity(); ?>">
                    <td><?php echo $file; ?></td>
                    <td>
                        <?php foreach ($error as $issue => $deviation) : ?>
                            <div>
                                <strong> <?php echo $issue; ?> </strong>
                                is set to
                                <strong> <?php echo $deviation; ?> </strong>
                            </div>
                        <?php endforeach; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</fieldset>
