<div class="entry-edit-head collapseable">
    <a><?php echo $this->getTitle(); ?></a>
</div>
<fieldset class="grid">
    <?php $rewrites = $this->getRewrites(); ?>
    <?php if (is_array($rewrites) && !empty($rewrites)) : ?>
    <table class="border">
        <thead>
            <tr class="headings">
                <th>Node</th>
                <th>New Value</th>
                <th>Old Value</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($rewrites as $rewrite) : ?>
                <tr class="<?php echo $this->getParity(); ?>">
                    <td>
                        <div>
                            <strong>File :</strong>
                            <?php echo $rewrite['file']; ?>
                        </div>
                        <div>
                            <strong>XML Path :</strong>
                            <?php echo $rewrite['path']; ?>
                        </div>
                    </td>
                    <td>
                        <strong> <?php echo $rewrite['newValue']; ?> </strong>
                    </td>
                    <td>
                        <strong> <?php echo $rewrite['oldValue']; ?> </strong>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php else : ?>
    <table class="border">
        <thead>
            <tr class="headings">
                <th>** No conflicting configuration rewrites **</th>
            </tr>
        </thead>
    </table>
    <?php endif; ?>
</fieldset>
