<?php /* var $this Bronto_Common_Block_Adminhtml_System_Config_About */ ?>

<div style="background-color: #f4f9f5; border: 1px solid #D6D6D6; margin-bottom: 10px; padding: 10px 5px 15px 30px; color: #000">
    <a href="http://www.bronto.com" target="_blank" title="Bronto Software Homepage"><img src="<?php echo $this->getSkinUrl('bronto/images/logo.jpg') ?>" /></a>
    <?php if ($this->getModuleNamespace() === 'bronto_common'): ?>
        <br />
        <strong>
            <?php echo $this->getModuleName(); ?> <?php echo $this->getModuleVersion(); ?>
            (<a href="http://a.bron.to/magento" target="_blank" title="Bronto Magento Extension Documentation">Documentation</a>)
        </strong>
        <br />
        <span style="color: #666">Copyright &copy; 2011-<?php echo date('Y'); ?></span>
        <span style="color: #ccc">|</span>
        <a href="mailto:info@bronto.com" target="_blank">info@bronto.com</a>
    <?php endif; ?>
</div>
